
version: "3.3"
services:
  employees:
    build:
      context: .
      dockerfile: Dockerfile
    restart:
      unless-stopped
    depends_on:
      - dbservice
    links:
      - dbservice
    ports:
      - "8081:8080"
    environment:
      MYSQL_HOST: dbservice
      MYSQL_DB: docker
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Password.123
  dbservice:
    image: mysql:5
    ports:
      - "3307:3306"
    restart:
      unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Password.123
      MYSQL_DATABASE: docker
#    volumes:
#       - ./mysql-data:/var/lib/mysql
#volumes:
#   mysql-data:
#     driver: local